services:
  - type: web
    name: django-api
    env: python
    plan: free
    buildCommand: "./build.sh"
    startCommand: "gunicorn ecommerce_api.wsgi:application"
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: ecommerce_api.settings
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: DATABASE_URL
        fromDatabase:
          name: django-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: False

databases:
  - name: django-db
    plan: free

